/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_stuefe_repros_SimpleJNI */

#ifndef _Included_de_stuefe_repros_SimpleJNI
#define _Included_de_stuefe_repros_SimpleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_stuefe_repros_SimpleJNI
 * Method:    printArrayAsHex
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_de_stuefe_repros_SimpleJNI_printArrayAsHex
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
